Creating BasicSearchAlgorithm...
Starting training with BasicSearchAlgorithm...
Training batch size: 1
Number of threads: 20
Evaluating agent (iteration 0): 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3/3 [00:26<00:00,  8.80s/it]
[Step 0] [92mTest score: 0.3333333333333333[0m
Forward pass (batch size: 1): 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:42<00:00, 42.24s/it]
Generating 3 proposals: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3/3 [00:28<00:00,  9.50s/it]
Validating proposals: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 50/50 [01:47<00:00,  2.14s/it]

[1;31mGive Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new[0m
LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.
Validating proposals:   0%|                                                                                     | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/utils.py", line 48, in _run
    return await tqdm_asyncio.gather(*tasks, desc=description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/tau/lib/python3.12/site-packages/tqdm/asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
           ^^^^^^^
  File "/opt/anaconda3/envs/tau/lib/python3.12/asyncio/tasks.py", line 627, in _wait_for_one
    f = await done.get()
        ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/tau/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xuanfeiren/Documents/tau-bench/tau_agent_opt.py", line 512, in <module>
    main()
  File "/Users/xuanfeiren/Documents/tau-bench/tau_agent_opt.py", line 501, in main
    algorithm.train(**train_params)
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/algorithms/basic_algorithms.py", line 436, in train
    return super().train(guide, train_dataset, num_epochs=num_epochs, batch_size=batch_size,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/algorithms/basic_algorithms.py", line 240, in train
    score = self.update(outputs, verbose=verbose, num_threads=num_threads, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/algorithms/basic_algorithms.py", line 380, in update
    self.optimizer_step(verbose=verbose, num_threads=num_threads, **kwargs)  # update the agent
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/algorithms/basic_algorithms.py", line 478, in optimizer_step
    score = validate()  # check the score on the validation set
            ^^^^^^^^^^
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/algorithms/basic_algorithms.py", line 448, in validate
    scores = evaluate(self.agent,
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/evaluators.py", line 38, in evaluate
    scores = _evaluate(agent, guide, indices)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/utils.py", line 127, in _fun
    outputs = async_run([fun] * batch_size, args_list=args_list, kwargs_list=kwargs_list,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/utils.py", line 51, in async_run
    return asyncio.run(_run())
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/tau/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/tau/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/tau/lib/python3.12/asyncio/base_events.py", line 678, in run_until_complete
    self.run_forever()
  File "/opt/anaconda3/envs/tau/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/opt/anaconda3/envs/tau/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/opt/anaconda3/envs/tau/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/xuanfeiren/Documents/tau-bench/Trace/opto/trainer/utils.py", line 42, in _run
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/tau/lib/python3.12/concurrent/futures/_base.py", line 647, in __exit__
    self.shutdown(wait=True)
  File "/opt/anaconda3/envs/tau/lib/python3.12/concurrent/futures/thread.py", line 239, in shutdown
    t.join()
  File "/opt/anaconda3/envs/tau/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/opt/anaconda3/envs/tau/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/tau/lib/python3.12/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

Step 6: Non-retryable error: cannot schedule new futures after shutdown
Step 5: Non-retryable error: cannot schedule new futures after shutdown
Step 5: Non-retryable error: cannot schedule new futures after shutdown
Step 6: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Exception ignored in: <module 'threading' from '/opt/anaconda3/envs/tau/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tau/lib/python3.12/threading.py", line 1594, in _shutdown
    atexit_call()
  File "/opt/anaconda3/envs/tau/lib/python3.12/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/opt/anaconda3/envs/tau/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/opt/anaconda3/envs/tau/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
Step 6: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
Step 7: Non-retryable error: cannot schedule new futures after shutdown
